Add IDisposable support to Mailosaur
mailosaur/mailosaur-dotnet pull request #23
Opened 2022-10-04 07:41 UTC by dantheman999301

2022-10-13 08:47 UTC, hippyhorse requested changes
Minor change required to Exception tests

2022-10-13 08:47 UTC, hippyhorse commented on Mailosaur.Test/ErrorsTests.cs
> +            MailosaurException ex;
Thanks for this contribution! Please could you just change the syntax of each of these exception tests as follows, we can then merge:

```csharp
using (var client = new MailosaurClient("invalid_key"))
{
    var ex = Assert.Throws<MailosaurException>(delegate
    {
        client.Servers.List();
    });

    Assert.Equal("Authentication failed, check your API key.", ex.Message);
}
```

2022-10-13 08:47 UTC, hippyhorse commented on Mailosaur.Test/ErrorsTests.cs
> +            MailosaurException ex;
See other comment

2022-10-13 08:47 UTC, hippyhorse commented on Mailosaur.Test/ErrorsTests.cs
> +            MailosaurException ex;
See other comment

2022-11-08 19:17 UTC, hippyhorse commented
Merged as part of https://github.com/mailosaur/mailosaur-dotnet/commit/463a10f00a7d96f016a73ad92ae87f16f028e4d5

2022-11-08 19:17 UTC, closed without merging

2022-11-10 08:20 UTC, dantheman999301 commented
@hippyhorse apologies, I've only just seen this! Thanks for changing the tests